name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Use the Node.js version that matches your project

    - name: Install Dependencies
      run: npm install

    - name: Build and Start Server
      run: |
        npm run build
        npm run start &
      env:
        # Set environment variables needed for your server if any
        NEXT_PUBLIC_API_URL: 'http://localhost:3000'
        DATABASE_URL: ${{secrets.env.DATABASE_URL}}
        GOOGLE_CLIENT_ID: ${{secrets.env.GOOGLE_CLIENT_ID}}
        GOOGLE_CLIENT_SECRET: ${{secrets.env.GOOGLE_CLIENT_SECRET}}
        NEXTAUTH_SECRET: ${{secrets.env.NEXTAUTH_SECRET}} 
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{secrets.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}}
        PUSHER_APP_ID: ${{secrets.env.PUSHER_APP_ID}} 
        NEXT_PUBLIC_PUSHER_APP_KEY: ${{secrets.env.NEXT_PUBLIC_PUSHER_APP_KEY}} 
        PUSHER_SECRET: ${{secrets.env.PUSHER_SECRET}}
        cluster: ${{secrets.env.cluster}} 
        REDIS_URL: ${{secrets.env.REDIS_URL}}


    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 60 # Increase this if your server takes longer to start
